const mongoose = require("mongoose");
const { Schema, model, models } = mongoose;

const rutineSchema = new Schema(
  {
    athlete_id: {
      type: Number,
      unique: true,
      required: true,
      minLenght: [9, "Minimo 9 caracteres"],
    },
    pe1: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pe2: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pe3: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pe4: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pe5: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pe6: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pe7: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pe8: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pe9: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pe10: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    b1: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    b2: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    b3: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    b4: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    b5: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    b6: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    b7: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    b8: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    b9: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    b10: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pi1: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pi2: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pi3: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pi4: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pi5: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pi6: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pi7: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pi8: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pi9: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pi10: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    e1: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    e2: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    e3: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    e4: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    e5: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    e6: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    e7: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    e8: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    e9: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    e10: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    e11: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    h1: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    h2: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    h3: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    h4: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    h5: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    h6: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    h7: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    h8: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    h9: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    h10: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    a1: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    a2: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    a3: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    a4: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    a5: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    a6: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    a7: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    a8: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    a9: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    a10: {
      active: { type: Boolean, require: true },
      serie: { type: Number, require: true },
      reps: { type: Number, require: true },
      musculo: { type: String, require: true },
      ejercicio: { type: String, require: true },
    },
    pecho: {
      lunes: { type: Boolean, require: true },
      martes: { type: Boolean, require: true },
      miercoles: { type: Boolean, require: true },
      jueves: { type: Boolean, require: true },
      viernes: { type: Boolean, require: true },
      sabado: { type: Boolean, require: true },
    },
    brazos: {
      lunes: { type: Boolean, require: true },
      martes: { type: Boolean, require: true },
      miercoles: { type: Boolean, require: true },
      jueves: { type: Boolean, require: true },
      viernes: { type: Boolean, require: true },
      sabado: { type: Boolean, require: true },
    },
    espalda: {
      lunes: { type: Boolean, require: true },
      martes: { type: Boolean, require: true },
      miercoles: { type: Boolean, require: true },
      jueves: { type: Boolean, require: true },
      viernes: { type: Boolean, require: true },
      sabado: { type: Boolean, require: true },
    },
    piernas: {
      lunes: { type: Boolean, require: true },
      martes: { type: Boolean, require: true },
      miercoles: { type: Boolean, require: true },
      jueves: { type: Boolean, require: true },
      viernes: { type: Boolean, require: true },
      sabado: { type: Boolean, require: true },
    },
    abdomen: {
      lunes: { type: Boolean, require: true },
      martes: { type: Boolean, require: true },
      miercoles: { type: Boolean, require: true },
      jueves: { type: Boolean, require: true },
      viernes: { type: Boolean, require: true },
      sabado: { type: Boolean, require: true },
    },
    hombros: {
      lunes: { type: Boolean, require: true },
      martes: { type: Boolean, require: true },
      miercoles: { type: Boolean, require: true },
      jueves: { type: Boolean, require: true },
      viernes: { type: Boolean, require: true },
      sabado: { type: Boolean, require: true },
    },
  },
  {
    timestamps: true,
  }
);

const Rutine = models.Rutine || model("Rutine", rutineSchema);
module.exports = Rutine;
